### ISSUE TITLE
Compile error in Release

### ISSUE THREAD

**Issue by windywater** [sunqueen/vlc-2.2.6.32-2013#1]
Debug mode is ok, but a lot of errors in Release mode, and I found the configs of the projects are incomplete, such as PrecompiledHeader, AdditionalIncludeDirectories... so should I modify all the project configs one by one?

**Comment by sunqueen** [comment]
Hi.

I'm not sure what is problem.
Because, I don't have experience with release version.
I hope you'll find your way to fix that.

This is list of use

vlc-contrib-i686-w64-mingw32-20160218.tar.bz2
qt4 : 4.8.5
game-music-emu-0.6.0.tar.bz2
harfbuzz-0.9.19.tar.bz2
libmodplug-0.8.8.5.tar.gz
live.2011.12.23.tar.gz
sidplay-libs-2.1.1.tar.gz

Bye.
